### ISSUE TITLE
PopOut issue with some unknown module

### ISSUE THREAD

**Issue by phil-the-dev** [League-of-Foundry-Developers/fvtt-module-popout#49] opened 2021-05-12 13:51 UTC
So I've been using the module for a while now, and though I don't know what module is causing the issue, but in combat when it's an NPC's turn, I'll get 2 windows per NPC's turn usually and then somehow it'll generate a ton of screens that end up blank and one that has the sheet. If I close the windows between turns, the NPC sheet won't popup anymore because I guess another window was proxying the request.

Let me know what other information you need; I realize this may be another module's abuse of foundry's mechanics, but am starting here for now.
![popout-issue](https://user-images.githubusercontent.com/1228950/117985610-dafb2580-b306-11eb-84d2-24974205df65.png)

**Comment by Posnet** [comment] 2021-05-14 00:27
I'll need to know the browser you are using, its version, the foundry version and the version of PopOut you are using. 

Could you please try disabling any adblock extensions you have enabled for foundry, they are one of the more common causes of strange popout behavior.

As well,
 - do you mean that when you click the popout button it produced 2 popped out windows?
 - or do you mean that as combat progress new windows *popout* without any interaction on your part?

**Comment by phil-the-dev** [comment] 2021-05-18 00:09
hey @Posnet, sorry for not posting for a few days, github email notifications were turned off for some reason. Here's all the info:

Happens in Firefox v89 and Chrome v90, both with my adblock extensions turned off.
Foundry Version: 0.7.9
PopOut Version: 1.2

So whenever I enter into combat mode and it's an NPC's turn, it's character sheet engages in "PopOut" mode automatically without my interaction out side of moving to the next person in turn order. When it's early in combat it'll show 2 windows, but it seems to evolve to opening more windows than 2 over time but I have no idea what could be causing the increase.

**Comment by phil-the-dev** [comment] 2021-05-18 00:13
Also with playing turning on/off modules, it looks like it may be an issue with the module "Next Up" that would automatically open/close character sheets for my NPCs.

**Comment by Posnet** [comment] 2021-05-19 22:12
Has the Next Up module ever working as intended with PopOut for you? or is this duplicate popouts new behavior.

**Comment by kandashi** [comment] 2021-05-24 15:33
Hey @Posnet, Im the dev of Next Up. The way I'm calling the popout command is probably very akward and hacky, so im not supprised its broken somwhere. 
Is there a snip you can provide for an easy way for an external module to force a popout?

**Comment by Posnet** [comment] 2021-05-29 05:59
@kandashi I am working on a public api function that you can use in the dev branch of this repo. I'll let you know when I am able to make a new release.

**Comment by kandashi** [comment] 2021-05-29 07:28
Thanks, that sounds great 👍

**Comment by Posnet** [comment] 2021-06-21 16:56
Apologies for the delay. I will release the new version in the next few days.

**Comment by Posnet** [comment] 2021-06-23 22:34
@kandashi  The new version now has an actual function you can call to popout windows.

**Comment by Posnet** [comment] 2021-07-01 02:39
I am closing this, since the ability to popout windows is now available by an official API. 
Feel free to re-open if you encounter issues with the API.

**Closed by Posnet** 2021-07-01 02:39 UTC
