### ISSUE TITLE
Typing in PopOut windows and Configure Controls shortcuts

### ISSUE THREAD

**Issue by lipefl** [League-of-Foundry-Developers/fvtt-module-popout#76] opened 2022-03-10 18:21 UTC
When using a popout window and you use one of the "Configure Controls" shortcuts, it acts like I was in the main window using the shortcut. 
For example: if i try to put number 2,4,6 or 8 using numpad in the name field of a PopOut sheet, it'll move the screen, instead of typing. It doesn't happen if i use the sheet without PopOut.

Tested using Savage Worlds SWADE system

Maybe a useful information: it wasn't happening when i was using PopOut 1.0, it started when i upgrade PopOut to the last version.

**Comment by Dialectikal** [comment] 2022-03-12 08:46
Also tested with the DnD5e system

**Comment by Posnet** [comment] 2022-03-13 00:41
Thanks, I am aware of this issue an am working on a fix. This was caused by https://github.com/League-of-Foundry-Developers/fvtt-module-popout/commit/e9e127381340975a224c5220dfa7e276858bd911

**Comment by supernun** [comment] 2022-03-13 06:41
Which version has this fix? On forge I have 2.7 and it still exhibits this issue.

**Comment by Posnet** [comment] 2022-03-13 07:06
What browser and OS are you using?

**Comment by Posnet** [comment] 2022-03-13 07:18
Nevermind, I worked out what the issue was. should be fixed in 2.8.

**Closed by Posnet** 2022-03-13 07:18 UTC

**Comment by supernun** [comment] 2022-03-13 22:08
Looks fixed to me! Thanks!
