### ISSUE TITLE
Linked Sheets etc. open in popped out window

### ISSUE THREAD

**Issue by Gondlar** [League-of-Foundry-Developers/fvtt-module-popout#32] opened 2020-10-28 11:12 UTC
When I pop out a journal entry which contains links to other entries/character sheets/.. and click on them to open them, their window opens in the popped out window rather than the main screen. 
![2020-10-28-115655_1247x521_scrot](https://user-images.githubusercontent.com/6443311/97427404-bdd7aa00-1914-11eb-90ca-ea011eb02569.png)

I've seen a roughly similar issue (#20) being closed because it is expected behaviour. Let me detail why I consider this a bug:

- The whole reason for popping out something is to have a window dedicated to that information. Having other windows floating above it negates that advantage
- Things opening in the popped out window cannot be dragged around. They permanently obscure part of the actual journal entry until you manage to click on that (which can be tricky if the window is large).
- Even then, they only glitch behind the actual journal entry. As a result they are unaccassible. Clicking on the link again neither brings them to foreground nor closes them. As a result, the link in the actual journal entry stops working.
- There is no way to bring those things back into the main window.

**Comment by kakaroto** [comment] 2020-10-28 15:07
Thanks for doing the research for old bugs ;) 
Not going to dismiss this one though because no, it's not expected behavior since popout was redesigned to prevent was what happening in #20 (which was a different use case).
I have a 1 second window where if a dialog is opened within 1 second of clicking on a popout, that new dialog is moved into the popout because it was created from it. This was added in the recent update and was intentional **however** it was only supposed to work on *dialogs*, like the "which level you want to cast this spell" or "is it an ability check or saving throw", "confirm the short rest" or the file browser for a new avatar, those kinds of dialogs. It was never supposed to be for full "Application windows" like a second journal entry.

So yeah, it's a bug, not intended, will be fixed. Thanks for reporting it!

**Comment by Posnet** [comment] 2021-02-24 13:23
Hi, I have taken over maintenance of this module. I will look into this issue as soon.

**Closed** 2021-05-02 03:34 UTC
