### ISSUE TITLE
PopOut doesn't work with PDFoundry PDFs

### ISSUE THREAD

**Issue by itinerant** [League-of-Foundry-Developers/fvtt-module-popout#33] opened 2020-10-28 22:19 UTC
I have a form-fillable pdf as a character sheet using the PDFoundry module.  It displays fine inside the main browser.  When I click PopOut, the window opens, but the pdf does not display.  Clicking PopIn at this point puts the window back in the main browser with pdf correctly displaying.

Foundry (0.7.5)
Simple-World Building system (0.4)
PDFoundry module (0.7.9)
PopOut! module (1.0)

**Comment by Jason-Terry** [comment] 2020-12-02 16:10
Same for me.

**Comment by mkscho63** [comment] 2020-12-24 00:35
Same for everyone in our group.

**Comment by jhirner** [comment] 2021-01-06 17:49
Same!
Both of these are really valuable modules, and it would be great to see them playing nicely together. It isn't clear to me if this is a PopOut! (v 1.0) issue or a PDFoundry (v 0.8.1) issue.

**Comment by caerandir** [comment] 2021-01-07 19:05
I'd second this - PopOut & PDFoundry are both extremely useful - and let me say thank you for providing this module! - and it would be _so_ nice to have them working together! (And sorry for just copying the same text from the PDFoundry bug tracker :-) )

**Comment by Posnet** [comment] 2021-02-24 13:25
Hi, I have taken over maintenance of this module. I will look into this issue soon. But I can guess that the issue is that PDFoundry has additional javascript libraries it needs initialized that are not being handled correctly.

**Comment by Dershem** [comment] 2021-04-04 02:53
Any updates on this?

**Comment by Posnet** [comment] 2021-04-18 15:07
I have spent spent some time on this one trying out different solutions. And while I was able to get the static PDFs working. I am not able to get the dynamic editable PDFs to work. 
The fundamental issue is that for security reasons **all** browsers completely reload `iframes` if they are moved within a DOM tree. Which includes migrating the iframe node to a new window.
This has the effect of resetting all event handlers on the iframe and so breaks any that have been set up by PDFoundry which uses pdfjs, which in turn uses IFrames. 
The only way I would be able to make it work on my end is if PDFoundry provided an API to completely re-initialize the iframe of a particular Foundry Application, but having a new DOM element be passed to it.

**Comment by jhirner** [comment] 2021-04-24 00:01
Wow, awesome. Thanks for the effort invested here!
FYI, I'm not sure if this is intentional or not, but it looks like that change was committed to the dev channel rather than the main channel; the updates therefore aren't readily installed by simply clicking the 'update' button in Foundry.

**Comment by Posnet** [comment] 2021-05-02 06:44
I am working with @kakaroto to organise a new release soon. It will be available then.

**Closed by Posnet** 2021-05-02 06:44 UTC
